services:
  db:
    container_name: picotrake_db
    image: postgres:14-alpine
    env_file:
      - .env.db
    networks:
      - picotrake-net
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d picotrake"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  api:
    build: .
    container_name: picotrake_api
    ports:
       - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.api
    networks:
      - picotrake-net
    restart: unless-stopped 

volumes:
  postgres_data:

networks:
  picotrake-net:
    driver: bridge
