CREATE DATABASE BBDD_projecte;

\c BBDD_projecte;

-- Tabla de SUSCRIPCIONES
CREATE TABLE SUSCRIPCIONES (
    id_suscripciones INT PRIMARY KEY,
    tipo VARCHAR(20) NOT NULL,
    precio FLOAT
);

-- Tabla de USUARIOS
CREATE TABLE USUARIOS (
    id_usuarios BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100),
    apellido VARCHAR(100),
    email VARCHAR(150) UNIQUE NOT NULL,
    contrasena VARCHAR(150) NOT NULL CHECK (LENGTH(contrasena) >= 6),
    fecha_registro DATE DEFAULT CURRENT_DATE,
    id_suscripciones INT NOT NULL DEFAULT 1, 
    fecha_inicio_suscripcion DATE DEFAULT CURRENT_DATE,
    fecha_final_suscripcion DATE NULL,
    FOREIGN KEY (id_suscripciones) REFERENCES SUSCRIPCIONES(id_suscripciones) ON DELETE CASCADE

);

-- Tabla de RUTAS
CREATE TABLE RUTAS (
    id_ruta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_ruta VARCHAR(100),
    dificultad VARCHAR(50),
    ubicacion VARCHAR(150),
    descripcion VARCHAR(255),
    duracion TIME
);

-- Tabla de HISTORIAL DE ACTIVIDADES
CREATE TABLE historial_actividades (
    id_historial BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuarios BIGINT,
    id_ruta BIGINT,
    fecha DATE,
    FOREIGN KEY (id_usuarios) REFERENCES USUARIOS(id_usuarios) ON DELETE CASCADE,
    FOREIGN KEY (id_ruta) REFERENCES RUTAS(id_ruta) ON DELETE CASCADE
);

-- Tabla de ANUNCIOS
CREATE TABLE ANUNCIOS (
    id_anuncios BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(100),
    contenido VARCHAR(225),
    id_suscripciones INT,
    FOREIGN KEY (id_suscripciones) REFERENCES SUSCRIPCIONES(id_suscripciones) ON DELETE CASCADE
);

-- Tabla de relación SUSCRIPCIONES-ANUNCIOS
CREATE TABLE SUSCRIPCIONES_ANUNCIOS (
    id_SA  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_suscripciones BIGINT,
    id_anuncios BIGINT,
    num_veces_mostrado INT,
    FOREIGN KEY (id_suscripciones) REFERENCES SUSCRIPCIONES(id_suscripciones) ON DELETE CASCADE,
    FOREIGN KEY (id_anuncios) REFERENCES ANUNCIOS(id_anuncios) ON DELETE CASCADE
);